/**
 * GAME BALANCE CONFIGURATION
 * 
 * This file contains ALL tuneable parameters for The Watch.
 * Edit these values to adjust game difficulty and outcomes.
 * Changes take effect immediately on page reload.
 * 
 * QUICK TIPS:
 * - Higher corruption rates = faster warden corruption
 * - Higher trust erosion = citizens lose faith faster
 * - Higher crime rates = more crimes generated
 * - Lower thresholds = easier to achieve good outcomes
 */

// ============================================================================
// GAME STRUCTURE
// ============================================================================

export const GAME_STRUCTURE = {
  // Number of days to simulate before final audit
  // Default: 3 (quick playthrough)
  // Increase to 5-7 for more data, longer games
  totalDays: 5,

  // Initial citizen trust distribution
  // These numbers should add up to total civilians (10 - 2 wardens = 8)
  // Adjust to test different starting conditions
  initialTrustDistribution: {
    trusting: 2,   // Start with 3 trusting citizens
    neutral: 3,    // Start with 3 neutral citizens
    wary: 3,       // Start with 2 wary citizens
    hostile: 2,    // Start with 0 hostile citizens
    // Total: 8 civilians (10 total - 2 wardens)
  },
};

// ============================================================================
// CRIME GENERATION
// ============================================================================

export const CRIME_CONFIG = {
  // Base probability that a civilian commits a crime per day (0.0 to 1.0)
  // Default: 0.05 (5% chance per civilian per day)
  // Higher = More crimes from citizens
  baseCitizenCrimeProbability: 1.0,

  // Trust level multipliers for crime probability
  // These multiply the base probability based on citizen trust
  trustMultipliers: {
    // Wary citizens are X times more likely to commit crimes
    // Default: 1.5 (50% more likely)
    wary: 2.0,
    
    // Hostile citizens are X times more likely to commit crimes
    // Default: 2.0 (100% more likely)
    hostile: 4.0,
  },

  // Maximum crime probability cap (0.0 to 1.0)
  // Prevents any single citizen from having too high a chance
  // Default: 0.3 (30% max)
  maxCrimeProbability: 1.0,

  // Location-based crime generation multiplier
  // This is multiplied by grid square's crime density
  // Default: 0.08 (8% at density 1.0)
  // Higher = More random crimes in high-density areas
  locationCrimeMultiplier: 0.16,

  // Corrupt warden crime generation threshold
  // Wardens above this corruption % generate fake crimes in quiet areas
  // Default: 30 (wardens at 30%+ corruption manufacture incidents)
  corruptWardenThreshold: 1,

  // Number of fake crimes generated by corrupt wardens [min, max]
  // Default: [1, 2] (1-2 fake crimes when bored)
  corruptCrimeRange: [1, 4],
};

// ============================================================================
// CRIME RESOLUTION
// ============================================================================

export const RESOLUTION_CONFIG = {
  // Base prevention chance when warden is in patrol zone (0.0 to 1.0)
  // Default: 0.30 (30% chance to prevent crime before it happens)
  // Higher = More effective wardens
  basePreventionChance: 0.30,

  // How much corruption reduces prevention (divisor)
  // Prevention = base - (corruption / this value)
  // Default: 500 (corruption of 100 reduces prevention by 0.20)
  // Higher = Corruption matters less
  // Lower = Corruption matters more
  corruptionPenaltyDivisor: 500,

  // Citizen reporting probabilities without warden present
  // These are base trust scores (0-100) multiplied by reportingMultiplier
  citizenReporting: {
    // Multiplier for reporting chance (0.0 to 1.0)
    // Default: 0.8 (80% of trust score becomes reporting chance)
    // Example: "trusting" citizen (70 trust) = 56% reporting chance
    reportingMultiplier: 0.8,

    // Trust score values for calculation (don't change unless you know what you're doing)
    trustScores: {
      trusting: 70,
      neutral: 50,
      wary: 30,
      hostile: 10,
    },
  },

  // Random reporting chance when no citizens nearby (0.0 to 1.0)
  // Default: 0.3 (30% chance someone reports anyway)
  randomReportingChance: 0.3,
};

// ============================================================================
// WARDEN CORRUPTION
// ============================================================================

export const CORRUPTION_CONFIG = {
  // Base corruption increase per day (0-100)
  // Default: 5 (wardens gain 5% corruption each day minimum)
  // Higher = Wardens corrupt faster
  // Lower = Wardens stay clean longer
  baseDailyIncrease: 25,

  // Boredom corruption bonus when warden has too few crimes in zone
  // Default: 10 (adds 10% corruption when < 2 crimes in zone)
  // Higher = Bored wardens corrupt much faster
  boredomBonus: 20,

  // Crime threshold for "boredom" to trigger
  // Default: 2 (< 2 crimes = bored)
  boredomThreshold: 1,

  // Burnout corruption bonus when warden has too many crimes in zone
  // Default: 8 (adds 8% corruption when > 8 crimes in zone)
  // Higher = Overwhelmed wardens corrupt faster
  burnoutBonus: 8,

  // Crime threshold for "burnout" to trigger
  // Default: 8 (> 8 crimes = burned out)
  burnoutThreshold: 8,

  // Corruption cap (0-100)
  // Default: 100 (wardens can become 100% corrupt)
  maxCorruption: 100,

  // Corruption level at which wardens start taking corrupt actions
  // Default: 40 (at 40%+ corruption, wardens log "corrupt actions")
  corruptActionThreshold: 10,

  // Chance of logging a corrupt action when above threshold (0.0 to 1.0)
  // Default: 0.4 (40% chance per day when corrupt enough)
  corruptActionChance: 0.8,
};

// ============================================================================
// CITIZEN TRUST
// ============================================================================

export const TRUST_CONFIG = {
  // Trust lost per warden nearby per day (-100 to 0)
  // Default: -2 (each warden near home costs 2 trust per day)
  // More negative = Surveillance erodes trust faster
  // Less negative = Citizens tolerate watch better
  watchExposurePenalty: -60,

  // Trust gained when crime victim receives good response
  // Default: 5 (prevented or responded crimes boost trust)
  goodResponseBonus: 5,

  // Trust lost when crime victim receives no response
  // Default: -15 (unreported crimes devastate trust)
  // More negative = Abandoned victims lose more trust
  noResponsePenalty: -75,

  // Trust score thresholds for classification (0-100)
  // These determine when citizens change trust levels
  trustThresholds: {
    // >= this score = "trusting"
    trusting: 60,
    
    // >= this score but < trusting = "neutral"  
    neutral: 40,
    
    // >= this score but < neutral = "wary"
    wary: 20,
    
    // < wary = "hostile"
  },
};

// ============================================================================
// AUDIT OUTCOMES
// ============================================================================

export const AUDIT_CONFIG = {
  // Outcome classification thresholds (0-100)
  // These determine which ending players get
  
  // "Balanced" outcome requirements (ideal but rare)
  // All three scores must meet or exceed these values
  balancedThresholds: {
    crimeControl: 70,    // Crime handling effectiveness
    corruption: 70,      // Warden integrity (inverse of corruption)
    trust: 70,          // Citizen trust level
  },

  // "Authoritarian" outcome requirements
  // High crime control BUT low corruption or trust
  authoritarianThresholds: {
    crimeControl: 70,    // Must be effective at crime
    corruptionMax: 40,   // BUT corruption score must be below this
    trustMax: 40,        // OR trust score must be below this
  },

  // "Neglectful" outcome requirements  
  // Low crime control BUT high trust
  neglectfulThresholds: {
    crimeControlMax: 50, // Crime handling must be below this
    trust: 60,           // BUT trust must be above this
  },

  // "Chaos" outcome requirements
  // Everything is bad
  chaosThresholds: {
    crimeControlMax: 50,  // Crime handling below this
    corruptionMax: 50,    // AND corruption score below this
    trustMax: 50,         // AND trust below this
  },

  // Everything else = "Mixed" outcome
};

// ============================================================================
// SCORE CALCULATIONS
// ============================================================================

export const SCORE_CONFIG = {
  // Crime control score weights (these multiply crime counts)
  // Higher weight = more impact on score
  crimeWeights: {
    prevented: 1.0,   // Prevented crimes count fully
    responded: 0.8,   // Responded crimes count 80%
    reported: 0.4,    // Reported crimes count 40%
    unreported: 0.0,  // Unreported crimes count 0%
  },

  // Trust score weights (multiply trust level counts)
  trustWeights: {
    trusting: 100,    // Trusting citizens worth 100 points
    neutral: 50,      // Neutral citizens worth 50 points
    wary: 25,         // Wary citizens worth 25 points
    hostile: 0,       // Hostile citizens worth 0 points
  },
};

// ============================================================================
// PRESETS (OPTIONAL - FOR QUICK SWITCHING)
// ============================================================================

// Uncomment a preset and copy its values above to quickly try different modes

export const PRESETS = {
  // Original balance (harder, more punishing)
  ORIGINAL: {
    corruption: { base: 5, boredom: 10, burnout: 8 },
    trust: { watchPenalty: -2 },
    balanced: { thresholds: 70 },
  },

  // Easier mode (more forgiving, "Balanced" achievable)
  EASY: {
    corruption: { base: 3, boredom: 6, burnout: 5 },
    trust: { watchPenalty: -1 },
    balanced: { thresholds: 60 },
  },

  // Harder mode (brutal, realistic)
  HARD: {
    corruption: { base: 7, boredom: 15, burnout: 12 },
    trust: { watchPenalty: -3 },
    balanced: { thresholds: 75 },
  },
};

// ============================================================================
// EXPORT ALL
// ============================================================================

// Package everything for easy import
export const GAME_CONFIG = {
  crime: CRIME_CONFIG,
  resolution: RESOLUTION_CONFIG,
  corruption: CORRUPTION_CONFIG,
  trust: TRUST_CONFIG,
  audit: AUDIT_CONFIG,
  score: SCORE_CONFIG,
};

export default GAME_CONFIG;
